COMMAND = "manager"


PM_SPECIFICATION_FILE_NAME = "pm.config.json"

DEFAULT_TODO_FLAG = "TODO"
DEFAULT_OBJECTIVE_FLAG = "@OBJECTIVE"

TITLE_PLACEHOLDER = "%TITLE%"
OBJECTIVE_NAME_PLACEHOLDER = "%NAME%"

V_QUIET = 0
V_NORMAL = 1
V_VERBOSE = 2

